try again

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -45,11 +45,13 @@ jobs:
           ruby-version: '3.3.4'
           bundler-cache: true
 
-      - name: release gem
+      - name: publish gem
         env:
           DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}
         run: |
+          test -n "$DOTENV_PRIVATE_KEY_CI" || (echo "Missing DOTENV_PRIVATE_KEY_CI secret" && exit 1)
           curl -fsS https://dotenvx.sh/install.sh | sh
           export PATH="$HOME/.dotenvx/bin:$PATH"
           export RUBYGEMS_API_KEY="$(dotenvx get RUBYGEMS_API_KEY -f .env.ci)"
-          bundle exec rake release
+          bundle exec rake build
+          gem push pkg/*.gem
